version: 0.2

phases:
    pre_build:
      commands:
        - echo Installing Dependencies
        - npm install
    build:
      - echo Building...
      - npm run build
    artifacts:
      files:
        - '**/*'
    discard-paths: no
    base-directory: build