version: 0.2

phases:
  install:
    commands:
      - echo Installing node 16...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash
      - apt install -y nodejs
      - echo Installing yarn
      - npm install --global yarn
    pre_build:
      commands:
        - echo Installing Dependencies
        - yarn
    build:
      - echo Yarn Building...
      - yarn build
    artifacts:
      files:
        - "**/*"
    discard-paths: no
    base-directory: build