version: 0.2

phases:
  install:
    commands:
      - echo Installing node 16...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash
      - apt install -y nodejs
    pre_build:
      commands:
        - echo Installing Dependencies
        - npm install
    build:
      - echo Building...
      - npm run build
    artifacts:
      files:
        - "**/*"
    discard-paths: no
    base-directory: build